### ISSUE TITLE
Error opening file /opt/data/hla.dmnd

### ISSUE THREAD

**Issue by andrewrech** [humanlongevity/HLA#1]
Hello,

I receive the following error when attempting to call on a file as described in the README.

```
docker run -v $TMPRAIDDIR:$TMPRAIDDIR -w $TMPRAIDDIR docker-dev.hli.io/xchao/hla \
    --sample_id test --input_bam_path $1.bam \
    --output_path ./test
[06/Jul/2017 18:35:55] INFO - Xie Chao's HLA typing algorithm
[06/Jul/2017 18:35:55] INFO - Sample_id: test Input file: test.bam
Extracting reads from S3
Aligning reads to IMGT database
processing FASTQ file
        found 11634 reads
processing MSA file
        found 26381 HLA exons
processing FASTQ file
Error: Error opening file /opt/data/hla.dmnd
        matched to 0 HLA exons
        0 reads matched to HLA types not in the MSA file
translating matches to MSA
Typing
Error in fread(align.path) : File is empty: hla-test/test.tsv
Execution halted
Traceback (most recent call last):
  File "/opt/bin/run.py", line 57, in <module>
    check_call([bin_path, args.input_bam_path, args.sample_id])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', 'test.bam', 'test']' returned non-zero exit status 1
```

It appears `hla.dmnd` is missing. I see one line about this file commented out in `data/script/batch.sh`:

> #diamond index hla.faa to hla.dmnd based on the DIAMOND version you are using

Thank you

**Comment by andrewrech** [comment]
`diamond makedb --in hla.faa -d hla`in /data

**Comment by hafizmtalha** [comment]
I am facing the following issue.. looks like a similar one.. but a bit different
 docker run -v `pwd`:`pwd` -w `pwd` humanlongevity/hla --sample_id 'SU-DIPG_24' --input_bam_path SU-DIPG-24.bam --output_path myoutput
[31/Jul/2022 11:37:10] INFO - Xie Chao's HLA typing algorithm
[31/Jul/2022 11:37:10] INFO - Sample_id: SU-DIPG_24 Input file: SU-DIPG-24.bam
typer.sh parameters: DELETE=false FULL=false
Extracting reads from S3
Aligning reads to IMGT database
processing FASTQ file
        found 5143 reads
processing MSA file
        found 26381 HLA exons
processing FASTQ file
        matched to 8 HLA exons
        16 reads matched to HLA types not in the MSA file
translating matches to MSA
Typing
Error in fread(align.path) : File is empty: hla-SU-DIPG_24/SU-DIPG_24.tsv
Execution halted
Traceback (most recent call last):
  File "/opt/bin/run.py", line 64, in <module>
    check_call(bin_args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bin/typer.sh', 'SU-DIPG-24.bam',
 'SU-DIPG_24']' returned non-zero exit status 1
