### ISSUE TITLE
An error in running get-reads-alt-unmap.sh script

### ISSUE THREAD

**Issue by Yiming-Shen** [humanlongevity/HLA#10]
I tried to run get-reads-alt-unmap.sh script:
`./get-reads-alt-unmap.sh my_file.bam processed.bam`
to pre-process a bam file but kept receiving error staring with:
`sambamba-view: Reference with name my_file.bam does not exist`
I was working in the directory where the bam file is in.

**Comment by tanghaibao** [comment]
@Yiming-Shen 
I tried to correct the sambamba command in the `get-reads-alt-unmap.sh` script. It should be ok now. Please let me know if you continue to have issues with it.

Haibao
