### ISSUE TITLE
I dont have any sudo permission on my institution's server, can I still install xHLA?

### ISSUE THREAD

**Issue by cjieming** [humanlongevity/HLA#18]
Hi it seems that xHLA requires Docker, which requires root access to use their daemon socket. Unfortunately I dont have root sudo access at my institution, is there another way I can install and use xHLA?

**Comment by tanghaibao** [comment]
@cjieming 
Check out the steps in the docker file:
https://github.com/humanlongevity/HLA/blob/master/docker/dev.dockerfile
for the dependencies, and then formatting the database:
https://github.com/humanlongevity/HLA/blob/master/docker/deploy.dockerfile

While installing some of these dependencies may still be easier with sudo access, but in many cases you may be able to get away with a local install.

**Comment by cjieming** [comment]
@tanghaibao 
got it. I am trying to install them one by one. 
Will then run run.py in bin folder to see if things are working. Thanks!
