### ISSUE TITLE
Missing HLA calls?

### ISSUE THREAD

**Issue by andrewrech** [humanlongevity/HLA#2]
Thank you for making this wonderful tool open source.

Installed according to `README`

`Linux master 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

`Docker version 17.06.0-ce, build 02c1d87`

```
docker run -v $(pwd):$(pwd) -w $(pwd) docker-dev.hli.io/xchao/hla \
    --sample_id $1:t:r --input_bam_path $1 \
    --output_path ./"$1:t:r_xhla"
```

> allele rank
> 1:     B*07:02   11
> 2:    C*06:103   NA
> 3:     C*07:02    6
> 4:  DPB1*01:01   NA
> 5: DRB1*13:171   NA

Do missing HLA calls imply that not enough quality reads were aligned? I can send representative `.bam`s privately.

`.tsv` from `full.r`: https://transfer.sh/M3Aa/andrewrech_example.tsv

Thank you

**Comment by tanghaibao** [comment]
@andrewrech what reference did you use for alignment? I've added a wiki page here: https://github.com/humanlongevity/HLA/wiki/BAMs-compatible-with-xHLA
We may need to do some preparation of BAMs here.

Haibao

**Comment by andrewrech** [comment]
@tanghaibao I used hg38 here: ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/hg38/Homo_sapiens_assembly38.fasta.gz

I will run these scripts now and see if I get a different result.

**Comment by tanghaibao** [comment]
@andrewrech this is probably why you don't get a lot of reads mapped in the respective regions on chr6. `Homo_sapiens_assembly38.fasta.gz` contains 525 HLA contigs (named like `>HLA-A*01:01:01:01`, `>HLA-DQB1*03:05:01` etc.) that should ideally be removed before mapping. 

You probably don't want to remap the whole thing against a new reference - if you look at the script [`bin/get-reads-alt.sh`](https://github.com/humanlongevity/HLA/blob/master/bin/get-reads-alt.sh#L10), you can see that we are trying to recover the reads from all these ALT contigs. Now for the Broad reference, we'll also need to append the 525 HLA contigs to that list.

Haibao

**Comment by andrewrech** [comment]
Thanks @tanghaibao. When I re-aligned using default bwa or as suggested in [bin/get-reads-alt.sh](https://github.com/humanlongevity/HLA/blob/master/bin/get-reads-alt.sh#L10), I got correct output. I will issue a PR for this, #3 and #4, combining `bin/get-reads-unmap.sh` and `bin/get-reads-alt.sh`:

```sh
sambamba view \
in.bam -f "bam" -h -p -l 0 -t $(nproc) \
-F "unmapped or mate_is_unmapped or (ref_name == 'chr6' and (position > 29844528 and position < 33100696)) or ref_name =~ /^HLA|chr6.*alt/" \
-o out.bam
```

I am happy to update the wiki if you would like as well.

Thank you very much for your help today.

**Comment by tanghaibao** [comment]
Thank you for the changes. I am also considering if we should get this BAM preparation script to run with the docker. Right now, the ENTRYPOINT for the docker is ```bin/run.py```, which assumes the BAM is good. We'll need to expose the BAM conversion script somehow.

Haibao

**Comment by andrewrech** [comment]
Accessing the script might be difficult for users unfamiliar with docker. I think having the script available in the repo and the wiki is sufficient. Additionally, users may want to add the script to existing workflows outside docker. Thus the docker container performs the one function of HLA calling, which is nice and tidy.

**Comment by tanghaibao** [comment]
@andrewrech thanks for the contribution. I have now updated wiki page: https://github.com/humanlongevity/HLA/wiki/BAMs-compatible-with-xHLA

Haibao
