### ISSUE TITLE
Do not hard code memory in get-reads-unmap.sh

### ISSUE THREAD

**Issue by andrewrech** [humanlongevity/HLA#4]
This will break for some users. Get memory with:

`$((( $(dmidecode -t 17 | grep "Size.*MB" | awk '{s+=$2} END {print s / 1024}') - 2500 )))MB`

To use available system memory minus a little.

**Comment by tanghaibao** [comment]
@andrewrech thanks. Would you consider putting this is a pull request?

**Comment by andrewrech** [comment]
@tanghaibao Yes, I am happy to PR these issues after resolving #2, which I will update after now re-aligning with bwa

thank you!
