### ISSUE TITLE
full resolution xHLA

### ISSUE THREAD

**Issue by nmcgranahan** [humanlongevity/HLA#9]
Hi, 
Thanks very much for making this resource available. 

I am not familiar with docker - but have successfully managed to get xHLA to run on my samples. However, I am unclear how to run xHLA in full resolution mode, to go beyond 4-digit resolution typing? Is there a simple way of achieving this? 

Thanks so much for your help, 
--Nicky

**Comment by tanghaibao** [comment]
@nmcgranahan 
I have added the option ``--full`` to allow full-digit typing. When you run the usual command, add this option. The results will be in a file that looks like ``hla-test/test.hla.full`` .

**Comment by nmcgranahan** [comment]
Thanks Haiboa - works beautifully. 
--Nicky
